#############################Application Values#############################
$SystemsList = ".\ServersList"
$PlatformVersion = "4.2.42.12"
$ApplicationVersion = "16.00.08.03"
$ODBCName = "LISTQAPLAT"
$DBServer = "QADB01"
$CoreIsseDB = "CCGS_QA_CoreIssue"
$CoreAuthDB = "CCGS_QA_CoreAuth"
$CoreCreditDB = "CCGS_QA_CoreCredit"
$CoreLibraryDB = "CCGS_QA_CoreLibrary"
$CoreAppDB = "CCGS_QA_CoreApp"
$CoreCollectDB = "CCGS_QA_CoreCollect"
$KMSDB = "CCGS_QA_KMS"
$MIPEndPoint = "Google.com"
$MIPPort = "81"
$HSMEndPoint = "Google.com"
$HSMPort = "443"
$AccountSummaryURL = "https://devwcf.platcc.com/CoreCardServices/CoreCardServices.svc"
$WCFURL = ""
$CoreCreditURL = ""
$CoreIssueURL = "www.google.com"
$ServicesURL = ""
$APIHumURL = ""
$KMS = "qaKMS01 qaKMS02"

